require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - ".git/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Metrics/LineLength:
  Max: 120

Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - git_source

Style/MultilineTernaryOperator:
  Enabled: false
