name: Linter

on: [push]

jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.7.x]
        bundler-version: [2.1.2]

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Installing Native Dependencies
        run: |
          sudo apt install libsqlite3-dev

      - name: Bundle install
        run: |
          gem install bundler --version=${{ matrix.bundler-version }}
          bundle install

      - name: RuboCop
        run: rubocop

  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn lint:eslint

  prettier:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn lint:prettier

  stylelint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn lint:stylelint
